site_name: OuterSpace OS
site_url: https://oos.alien6.com
site_author: Ludovic FERNANDEZ, Alien6
site_description: >-
  A lightweight, secure, and open-source operating system optimized for Machine Learning and Artificial Intelligence.

# Repository
repo_name: alien6-studio/outerspace-os
repo_url: https://github.com/alien6-studio/outerspace-os

# Copyright
copyright: Copyright &copy; 2023 Alien6

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/logo.png
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate

extra:
  generator: false

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Introduction: introduction.md
    - Key Features: features.md
  - About:
    - Sponsoring: about/sponsors.md
